// Code generated by command: go run asm.go -out query_amd64.s. DO NOT EDIT.

//go:build amd64 && !purego

#include "textflag.h"

// func queryCore(r *[8]uint64, bits [][8]uint64, hashes []uint32)
// Requires: SSE2, SSE4.1
TEXT ·queryCore(SB), NOSPLIT, $0-56
	MOVQ    r+0(FP), AX
	MOVQ    bits_base+8(FP), CX
	MOVQ    hashes_base+32(FP), DX
	MOVQ    hashes_len+40(FP), BX
	PCMPEQL X0, X0
	PCMPEQL X1, X1
	PCMPEQL X2, X2
	PCMPEQL X3, X3

loop:
	MOVL  (DX), SI
	SHLQ  $0x06, SI
	ADDQ  CX, SI
	PXOR  X4, X4
	MOVOU (SI), X5
	MOVOU 16(SI), X6
	MOVOU 32(SI), X7
	MOVOU 48(SI), X8
	PAND  X5, X0
	PAND  X6, X1
	PAND  X7, X2
	PAND  X8, X3
	POR   X0, X4
	POR   X1, X4
	POR   X2, X4
	POR   X3, X4
	PTEST X4, X4
	JZ    done
	ADDQ  $0x04, DX
	SUBQ  $0x01, BX
	JNZ   loop

done:
	MOVOU X0, (AX)
	MOVOU X1, 16(AX)
	MOVOU X2, 32(AX)
	MOVOU X3, 48(AX)
	RET
